# Generated by Django 4.0.4 on 2022-06-03 06:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_numbers_of_teams', models.PositiveIntegerField()),
                ('rank', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('coach', models.CharField(max_length=100, unique=True)),
                ('max_numbers_of_players', models.PositiveIntegerField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
        migrations.CreateModel(
            name='Season_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('point', models.FloatField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.team')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='management.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='management.team')),
            ],
        ),
    ]
