# Generated by Django 4.0.4 on 2022-06-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_player_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.team'),
        ),
    ]
